# Let's Show dem Erros ü•µ
![Errors got hands](../images/Damn-Errors.jpg)
‚Äã
Genau wie beim Pending State ist es wichtig, Fehler zu haben, denn unsere Nutzer wollen nicht verwirrt dasitzen und sich fragen, warum ihre Seite einfach leer ist oder unendlich lange l√§dt.

Wir brauchen eine M√∂glichkeit, den Fehler zu behandeln und dem Benutzer eine Nachricht im Template anzuzeigen.

Damit wir alles DRY halten k√∂nnen, gehen wir zur√ºck zu unserem benutzerdefinierten useFetch Hook und erstellen einen neuen Status f√ºr Fehler:

```jsx
const [error, setError] = useState(null);
```

Der Anfangswert wird null sein, weil wir keinen Fehler ganz am anfang haben, und wir haben bereits gesehen, dass durch try n catch unsere Fehler Objekte sind.

Wie ich oben sagte, werden wir unser gutes altes try und catch innerhalb unserer fetchData verwenden:

```jsx
    const fetchData = async () => {
        // unsere auf true gesetztes loading kann drau√üen bleiben
      setIsPending(true);


      try {
        const res = await fetch(url);
        const json = await res.json();
        setData(json);
        setIsPending(false);

        // extra f√ºr den Fall, dass unser vorheriger Fehler zwischengespeichert wird, wollen wir ihn wieder auf null setzen
        setError(null)
      } catch (e) {
        // jetzt k√∂nnen wir den Fehler einfach hier festlegen
        setError(e)
        // da wir unseren Fehler erhalten haben und ihn anzeigen wollen, wird das Laden nicht mehr ben√∂tigt
        setIsPending(false);
      }
    };
```
‚Äã
Nun, wie wir bereits gelernt haben, WENN kein wirklicher Fehler auftritt, wie z.B. das √Ñndern einer falschen URL, werden wir keinen Fehler erhalten, bis wir tats√§chlich einen neuen Fehler ausl√∂sen, wenn die Response nicht in Ordnung war.

Hinweis: Mit cra wird das Herumspielen mit url eine Menge Fehler ausl√∂sen, w√§hrend Vite sie ignoriert und fast nichts anzeigt

```jsx
      try {
        const res = await fetch(url);
        // direkt nachdem wir unsere Response erhalten haben, wollen wir einen neuen Fehler ausl√∂sen, wenn etwas schief geht
        console.log(res);
        if(!res.ok){
            // console.log immer deine Response, um zu sehen, wo ein Fehler oder ein Status-Text versteckt sein k√∂nnte, und benutze ihn dann. Falls du nichts findest, schreibe deinen eigenen String, um dem Benutzer mitzuteilen, dass etwas schief gelaufen ist.
            throw new Error(res.statusText)
        }
        const json = await res.json();
        setData(json);
        setIsPending(false);
        setError(null);
      }
```

Jetzt k√∂nnen wir den Fehler als Prop √ºbergeben, damit wir ihn in unseren Komponenten verwenden k√∂nnen

```jsx
return { data, isPending, error };
```

In TripList greifen wir wie immer zu unserer brandneuen, frischen Prop:

```jsx
const { data: trips, isPending, error } = useFetch(url);
```

Jetzt k√∂nnen wir unterhalb unseres Loading's und oberhalb unserer Trips eine Bedingung f√ºr unseren Fehler festlegen:

```jsx
{error && <h3>Error: {error.message}</h3>}
```
erledigt